### PR TITLE
fix: validate patched image tag

### LINKED ISSUE #490: [BUG] Invalid patched image tag causes copa to freeze
### Version of copa

0.6.0

### Expected Behavior

Supplying a patch image tag that is not compliant with OCI image tag requirements (such as any tag with the `+` character) should result in `copa` failing immediately due to the supplied tag not complying with tag regex requirements.

```bash
copa patch --image $registryname.azurecr.io/$image:tag02 --report trivy-os-scan-report.json --tag "-patched+1" --format="openvex" --output "vex.json"
```

### Actual Behavior

`copa` freezes at the final step of image building:

```
 => merge (docker-image://myacr.azurecr.io/foo-image:tag02, diff (apt update) -> (sh -c apt install --no-install-recommends --allow-ch  0.0s
 => ERROR exporting to docker image format                                                                                                                        0.3s
 => => exporting layers                                                                                                                                           0.3s
 => => exporting manifest sha256:062d7a5db6b4a677c14a88ed7899412a3e9c92f3b7ac742161f24a13ada46db9                                                                 0.0s
 => => exporting config sha256:65343399c1f090eba0a50d56133788e31c3a939e2d14aefba249a210b08e9b4d                                                                   0.0s
------
 > exporting to docker image format:
------
```

### Steps To Reproduce

Run `copa` but pass in an option where the patched tag is not valid.

```bash
copa patch --image $registryname.azurecr.io/$image:tag02 --report trivy-os-scan-report.json --tag "-patched+1" --format="openvex" --output "vex.json"
```

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by johnsonshi**
Passing invalid patched image tag causes copa to freeze. This fix validates the patched image tag.

Closes #490

### CODE REVIEW

File: pkg/patch/patch.go [hunk 1]
```diff
@@ -94,6 +94,11 @@ func patchWithContext(ctx context.Context, image, reportFile, patchedTag, workin
 			patchedTag = fmt.Sprintf("%s-%s", tag, defaultPatchedTagSuffix)
 		}
 	}
+	_, err = reference.WithTag(imageName, patchedTag)
+	if err != nil {
+		log.Errorf("invalid patched tag %s", patchedTag)
+		return err
```
Comment (sozercan) [inline pkg/patch/patch.go:100]: can we avoid the double log and wrap and return the error

something like
```suggestion
		return fmt.Errorf("%w with patched tag %s", err, patchedTag)
```

Comment (johnsonshi) [reply pkg/patch/patch.go]: image

**Review by sozercan — APPROVED** [review]
Thank you! LGTM
