### PR TITLE
fix: use temp rootfs for rpm install to preserve original image configs

### LINKED ISSUE #809: [BUG] openssl.cnf gets overwritten
### Version of copa

0.8.0

### Expected Behavior

openssl.cnf is not overwritten during patch. This does not happen with Mariner core image (mcr.microsoft.com/cbl-mariner/base/core)

### Actual Behavior

openssl.cnf is overwritten which may break certain configurations

### Steps To Reproduce

- Create `openssl.cnf` file with any data

- Create a Dockerfile with the following contents:
```
FROM mcr.microsoft.com/cbl-mariner/distroless/base:2.0.20240112
COPY openssl.cnf /etc/pki/tls/
```
> Please note that base image is specifically selected to pin to a version that has an openssl vulnerability

- Build image with `docker build -t openssl:test .`
- Notice custom `openssl.cnf` is in `/etc/pki/tls/` path. example: [https://oci.dag.dev/layers/sozercan/openssl@sha256:4f15e75c292a2fcb04e55ee4b93cb3449424b9360831490339d3132b1a31a735/etc/pki/tls/](https://oci.dag.dev/layers/sozercan/openssl:test@sha256:164dbe64a682513e341b6262646c8bee2fb72fca3801aedd9f720765704af995/etc/pki/tls/)
- Copa patch the image using `copa patch -i openssl:test`
- Notice patched image containing `openssl.cnf` is overwritten by copa: https://oci.dag.dev/layers/sozercan/openssl:test-patched@sha256:1d703d7013826dadde6c1ed3f32ce8b4b1431b8f1bbeedf7bc92863e2f20fda8/etc/pki/tls/

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### LINKED ISSUE #850: [BUG] copa overwrites /usr/sbin symlink for mariner distroless/debug
### Version of copa

v0.9.0

### Expected Behavior

copa should not change the existing directory structure and symlinks

### Actual Behavior

copa overwrites the existing symlink

### Steps To Reproduce

1. Check config for original image https://oci.dag.dev/layers/mcr.microsoft.com/cbl-mariner/distroless/debug@sha256:960d95cc274484fc72b33d4b5720857fbb1c9a5f35b93a39f8e161557236fd4d/
`70a0cf87 lrwxrwxrwx 0/0               0 2024-01-23 18:52 sbin -> usr/sbin`

2. `copa patch -i mcr.microsoft.com/cbl-mariner/distroless/debug:2.0.20241029`

3. Check config for patched image: https://oci.dag.dev/layers/sertacacr.azurecr.io/debug:2.0-patched@sha256:ffb2188eb72313a86dc3b0a00e903c2cbd0eda565a50bbc47038ec04b8b0b174/
`d0a2b129 drwxr-xr-x 0/0               0 2024-11-26 19:04 sbin`

Mariner 2 spec provides `/sbin` as the path and copa is extracting to that path since that's the path in the rpm. Copa should check if existing path is a symlink and follow the path instead of dropping the files
https://github.com/microsoft/azurelinux/blob/2.0/SPECS/busybox/busybox.spec#L94

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by ashnamehrotra**
Changes RPM install approach from downloads/extraction to using a temp rootfs with the rpm install command. This preserves norepalce files and symlinks from the original image.

Describe the changes in this pull request using active verbs such as _Add_, _Remove_, _Replace_ ...

Closes #809
Closes #850

### CODE REVIEW

File: pkg/pkgmgr/rpm.go [hunk 1]
```diff
@@ -599,99 +600,142 @@ func (rm *rpmManager) unpackAndMergeUpdates(ctx context.Context, updates unversi
...
+
+			if [ "$IGNORE_ERRORS" = "false" ] && [ $? -ne 0 ]; then
+				exit $?
 			fi
 		done
+
+		mkdir /tmp/rootfs/var/lib/rpmmanifest
+		
+		rpm --dbpath=/tmp/rootfs/var/lib/rpm -qa | tee /tmp/rootfs/var/lib/rpmmanifest/container-manifest-1
+		rpm --dbpath=/tmp/rootfs/var/lib/rpm -qa --qf '%{NAME}\t%{VERSION}-%{RELEASE}\t%{INSTALLTIME}\t%{BUILDTIME}\t%{VENDOR}\t%{EPOCH}\t%{SIZE}\t%{ARCH}\t%{EPOCHNUM}\t%{SOURCERPM}\n' | grep -v '^gpg-pubkey' | tee /tmp/rootfs/var/lib/rpmmanifest/container-manifest-2
```
Comment (sozercan) [inline pkg/pkgmgr/rpm.go:699]: we can do `rpm --dbpath=/tmp/rootfs/var/lib/rpm --erase --allmatches gpg-pubkey-*` instead of ignoring

File: pkg/pkgmgr/rpm.go [hunk 2]
```diff
@@ -599,99 +600,142 @@ func (rm *rpmManager) unpackAndMergeUpdates(ctx context.Context, updates unversi
...
+		rpm --dbpath=/tmp/rootfs/var/lib/rpm -qa | tee /tmp/rootfs/var/lib/rpmmanifest/container-manifest-1
+	
+		echo "testing just name"
+		rpm --dbpath=/tmp/rootfs/var/lib/rpm -qa --qf \"\%{NAME}\"
+
+		rpm --dbpath=/tmp/rootfs/var/lib/rpm -qa
+		rm /tmp/rootfs/var/lib/rpm
+		rm -rf /tmp/rootfs/var/cache/tdnf
+	
+		rpm --dbpath /tmp/rpmdb -qa ` + fmt.Sprintf(queryFormat, resultQueryFormat, pkgs, "/tmp/rootfs/manifest") + ``
```
Comment (sozercan) [inline pkg/pkgmgr/rpm.go:668]: is `pkgs` empty here?

Comment (sozercan) [reply pkg/pkgmgr/rpm.go:668]: i see it gets populated from downloadCmd

File: pkg/pkgmgr/rpm.go [hunk 3]
```diff
@@ -599,99 +600,142 @@ func (rm *rpmManager) unpackAndMergeUpdates(ctx context.Context, updates unversi
...
+
```
Comment (sozercan) [inline pkg/pkgmgr/rpm.go:669]: looks like this is going to fail validation because we are generating the manifest here, so the expected packages won't match

File: pkg/pkgmgr/rpm.go [hunk 4]
```diff
@@ -564,13 +564,14 @@ func (rm *rpmManager) unpackAndMergeUpdates(ctx context.Context, updates unversi
 	toolsInstalled := toolingBase.Run(llb.Shlex(installToolsCmd), llb.WithProxy(utils.GetProxy())).Root()
 	busyboxCopied := toolsInstalled.Dir(downloadPath).Run(llb.Shlex("cp /usr/sbin/busybox .")).Root()
 
+	// Retrieve all package info from image to be patched.
+	jsonPackageData, err := json.Marshal(rm.packageInfo)
```
Comment (sozercan) [inline pkg/pkgmgr/rpm.go:568]: can you separate this out and add unit tests

**Review by sozercan — APPROVED** [review]
added a comment, otherwise LGTM. Let's follow up with integration tests to validate symlink and `noreplace` files too
